---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
        - name: zigbee2mqtt
          image: docker.io/koenkk/zigbee2mqtt:1.42.0 # updateable version

          securityContext:
            privileged: true
            runAsGroup: 27 # dialout

          env:
            - name: TZ
              value: America/Los_Angeles

            - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER
              value: mqtt://mqtt-cleartext.mosquitto.svc.cluster.local:1883
            # - name: ZIGBEE2MQTT_CONFIG_MQTT_USER
            # - name: ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD

            - name: ZIGBEE2MQTT_CONFIG_SERIAL_PORT
              value: /dev/ttyUSB0

            - name: ZIGBEE2MQTT_CONFIG_ADVANCED_CHANNEL
              # set zigbee channel
              value: '25'

            - name: ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY
              valueFrom:
                secretKeyRef:
                  name: zigbee
                  key: network_key
            - name: ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID
              valueFrom:
                secretKeyRef:
                  name: zigbee
                  key: pan_id
            - name: ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID
              valueFrom:
                secretKeyRef:
                  name: zigbee
                  key: ext_pan_id

            - name: ZIGBEE2MQTT_CONFIG_HOMEASSISTANT
              # enable Home Assistant integration (via MQTT discovery)
              value: 'true'

            - name: ZIGBEE2MQTT_CONFIG_FRONTEND
              # enable web GUI
              value: 'true'

            - name: ZIGBEE2MQTT_CONFIG_LOG_OUTPUT
              value: 'console'

            # - name: DEBUG
            #   value: zigbee-herdsman*
            - name: ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL
              value: debug

          ports:
            - name: http
              containerPort: 8080

          resources:
            # limits:
            #   cpu: 250m
            #   memory: 1Gi
            # requests:
            #   cpu: 250m
            #   memory: 1Gi

          volumeMounts:
            - name: data
              mountPath: /app/data
            - name: skyconnect
              mountPath: /dev/ttyUSB0
            - name: udev
              mountPath: /run/udev
              readOnly: true

          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: skyconnect
          hostPath:
            path: /dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_065b344abf18ec11a1baeb9a47486eb0-if00-port0
        - name: udev
          hostPath:
            path: /run/udev
