---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      component: app
  strategy:
    # Only a single container can be running at a time because a lock is
    #   required on the Zigbee bridge.
    type: Recreate
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
        - name: zigbee2mqtt
          image: docker.io/koenkk/zigbee2mqtt:1.40.1 # updateable version

          securityContext:
            privileged: true
            runAsGroup: 27 # dialout

          env:
            - name: TZ
              value: America/Los_Angeles
            # - name: DEBUG
            #   value: zigbee-herdsman*

            - name: ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY
              valueFrom:
                secretKeyRef:
                  name: zigbee
                  key: network_key
            - name: ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID
              valueFrom:
                secretKeyRef:
                  name: zigbee
                  key: pan_id
            - name: ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID
              valueFrom:
                secretKeyRef:
                  name: zigbee
                  key: ext_pan_id

          volumeMounts:
            - name: data
              mountPath: /app/data
            - name: configuration
              mountPath: /app/data/configuration.yaml
              subPath: configuration.yaml
              readOnly: false
            - name: skyconnect
              mountPath: /dev/ttyUSB0
            - name: udev
              mountPath: /run/udev
              readOnly: true

          ports:
            - name: http
              containerPort: 8080

          resources:
            # limits:
            #   cpu: 250m
            #   memory: 1Gi
            # requests:
            #   cpu: 250m
            #   memory: 1Gi

          startupProbe:
            httpGet:
              port: http
              path: /
            # (12 * 10) seconds = 2 minutes
            periodSeconds: 10
            failureThreshold: 12
          livenessProbe:
            httpGet:
              port: http
              path: /
            initialDelaySeconds: 0
            failureThreshold: 3
            periodSeconds: 10

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: configuration
          configMap:
            name: z2m-config
            items:
              - key: configuration.yaml
                path: configuration.yaml
        - name: skyconnect
          hostPath:
            path: /dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_065b344abf18ec11a1baeb9a47486eb0-if00-port0
        - name: udev
          hostPath:
            path: /run/udev
