---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: oidc-client
spec:
  clientId: zigbee2mqtt
  name: zigbee2mqtt
  description: Zigbee to MQTT bridge for Home Assistant
  protocol: 'openid-connect'
  authorizationServicesEnabled: true
  # alwaysDisplayInConsole: true
  standardFlowEnabled: true
  implicitFlowEnabled: false
  directAccess: true
  public: false
  consentRequired: false
  frontChannelLogout: true
  fullScopeAllowed: true
  bearerOnly: false
  surrogateAuthRequired: false
  clientAuthenticatorType: client-secret
  realmRef:
    kind: ClusterKeycloakRealm
    name: sequoia
  secret: '$oidc:client_secret'
  webUrl: 'https://z2m.park.orleans.io'
  # homeUrl: 'https://z2m.park.orleans.io'
  attributes:
    display.on.consent.screen: 'false'
    backchannel.logout.revoke.offline.tokens: 'false'
    backchannel.logout.session.required: 'true'
    oauth2.device.authorization.grant.enabled: 'false'
    oidc.ciba.grant.enabled: 'false'
