# yaml-language-server: $schema=https://raw.githubusercontent.com/Koenkk/zigbee2mqtt/refs/tags/1.40.1/lib/util/settings.schema.json
# updateable version, keep in sync with container

# k8s config maps are read only, so we need to extract dynamic config to
#   external files
devices: 'devices.yaml'
groups: 'groups.yaml'

mqtt:
  server: 'mqtt://mqtt-cleartext.mosquitto.svc.cluster.local:1883'

serial:
  port: '/dev/ttyUSB0'
  adapter: 'ember'

advanced:
  # zigbee channel
  channel: 25

  log_output:
    - 'console'
  log_level: 'info'
  # https://www.zigbee2mqtt.io/guide/configuration/logging.html#reducing-mqtt-traffic
  # log_namespaced_levels:
  #     z2m:mqtt: 'warning'

# enable Home Assistant integration (via MQTT discovery)
homeassistant:
  enabled: true

frontend:
  enabled: true
  port: 8080
  url: 'https://z2m.park.orleans.io'
