# yaml-language-server: $schema=https://raw.githubusercontent.com/Koenkk/zigbee2mqtt/refs/tags/1.42.0/lib/util/settings.schema.json
# updateable version, keep in sync with container

version: 5

# k8s config maps are read only, so we need to extract dynamic config to
#   external files
devices: 'devices.yaml'
groups: 'groups.yaml'

mqtt:
  server: 'mqtt://mqtt-cleartext.mosquitto.svc.cluster.local:1883'
  base_topic: zigbee2mqtt

serial:
  adapter: 'zstack' # for SONOFF Zigbee 3.0 gateway
  port: '/dev/ttyUSB0'
  rtscts: true # enable hardware flow control, improving stability

advanced:
  # zigbee channel
  channel: 25

  log_output:
    - 'console'
  log_level: 'info'
  # https://www.zigbee2mqtt.io/guide/configuration/logging.html#reducing-mqtt-traffic
  # log_namespaced_levels:
  #     z2m:mqtt: 'warning'

availability:
  enabled: true

# enable Home Assistant integration (via MQTT discovery)
homeassistant:
  enabled: true

frontend:
  enabled: true
  port: 8080
  url: 'https://z2m.red.orleans.io'
