apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: edp-keycloak-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: keycloak-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: epmdedp
      version: '>=1.20.0 < 2.0.0'
  install:
    crds: Create
    createNamespace: true
  interval: 1h0m0s
  releaseName: edp-keycloak-operator
  targetNamespace: operators
  upgrade:
    crds: CreateReplace
  values:
    clusterReconciliationEnabled: true
