apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: matter-server
commonLabels:
  app: matter-server

resources:
  - namespace.yaml
  - storage.yaml
  - deployment.yaml
  - service.yaml
