apiVersion: v1
kind: Service
metadata:
  name: matter-server
  labels:
    monitor: matter-server
spec:
  selector:
    component: app
  ports:
    - name: websocket
      port: 5580
      targetPort: websocket
