# Reference:
# https://github.com/keycloak/keycloak/discussions/12594
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
        - name: "keycloak"
          image: "quay.io/keycloak/keycloak:23.0"
          args: ["start"]
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: admin
                  key: username
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin
                  key: password

            - name: "KC_PROXY"
              value: "edge"
            - name: "KC_HOSTNAME"
              value: "auth.gibbs.tk"
            - name: "KC_HEALTH_ENABLED"
              value: "true"
            - name: "KC_METRICS_ENABLED"
              value: "true"
            - name: "KC_SPI_ADMIN_REALM"
              value: "sequoia"

            - name: KC_DB
              value: postgres
            - name: KC_DB_URL_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: host
            - name: KC_DB_URL_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: port
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: password
            - name: "KC_DB_URL_DATABASE"
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: dbname
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 10m
              memory: 400Mi
            limits:
              cpu: 300m
              memory: 500Mi
          readinessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 30
            httpGet:
              path: /realms/sequoia
              port: 8080
