---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: 'keycloak-dashboard-https'
  namespace: keycloak
spec:
  entryPoints:
    - 'websecure'
  routes:
    - match: 'Host(`auth.orleans.io`)'
      kind: 'Rule'
      services:
        - kind: 'Service'
          name: 'keycloak'
          scheme: 'https'
          port: 8443
      # middlewares:
      #   - name: security-no-frame-deny
      #     namespace: kube-system
  tls:
    secretName: wildcard-orleans-io
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-insecure
  namespace: keycloak
  labels:
    monitor: keycloak
spec:
  selector:
    component: app
  ports:
    - name: http
      port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    monitor: keycloak
spec:
  selector:
    component: app
  ports:
    - name: https
      port: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-headless
  namespace: keycloak
spec:
  selector:
    component: app
  clusterIP: None
  sessionAffinity: None
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    - name: jgroups
      port: 7600
      protocol: TCP
      targetPort: jgroups
