apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
commonLabels:
  app: keycloak

resources:
  - namespace.yaml
  - database.yaml
  - deployment.yaml
  - ingress.yaml
  - operator-config.yaml
  - secrets.yaml
