apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: keycloak

resources:
  - namespace.yaml
  - database.yaml
  - certificates.yaml
  - deployment.yaml
  - ingress.yaml
  - secrets.yaml
  - resources/auth-flows.yaml
  - resources/base.yaml
  - resources/groups.yaml
  - resources/roles.yaml
