---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak

  instances: 1

  storage:
    size: 5Gi
# TODO: https://cloudnative-pg.io/
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: keycloak
spec:
  selector:
    component: postgressql-db
  type: NodePort
  ports:
    - name: pgql
      port: 5432
      protocol: TCP
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgressql-db
  namespace: keycloak
  labels:
    app: keycloak
spec:
  serviceName: postgressql-db-service
  replicas: 1
  selector:
    matchLabels:
      component: postgressql-db
  template:
    metadata:
      labels:
        component: postgressql-db
    spec:
      containers:
        - name: postgressql-db
          image: docker.io/library/postgres:16
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: database
                  key: database
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              cpu: 2000m
              memory: 500Mi
          volumeMounts:
            - name: keycloak-data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
      terminationGracePeriodSeconds: 60
      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pvc
  namespace: keycloak
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15G
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-pv
  labels:
    type: local
spec:
  capacity:
    storage: 15G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: keycloak-pvc
    namespace: keycloak
  local:
    path: /mnt/keycloak
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - monongahela
