---
apiVersion: v1.edp.epam.com/v1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  secret: keycloak
  url: https://auth.orleans.io
---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealm
metadata:
  name: sequoia
  namespace: keycloak
spec:
  realmName: sequoia
  keycloakOwner: main
