---
apiVersion: v1.edp.epam.com/v1alpha1
kind: ClusterKeycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  secret: admin
  url: https://auth.orleans.io
---
apiVersion: v1.edp.epam.com/v1alpha1
kind: ClusterKeycloakRealm
metadata:
  name: sequoia
  namespace: keycloak
spec:
  realmName: sequoia
  displayName: 'Sequoia'
  clusterKeycloakRef: keycloak
