apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scrutiny
commonLabels:
  app: scrutiny-master

resources:
  - namespace.yaml
  - database.yaml
  - storage.yaml
  - deployment.yaml
  - ingress.yaml
  - secrets.yaml
  - ../../../../services/forward-auth
