---
apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: cloudnative-pg
spec:
  namespace: operators
  source:
    sourceType: Catalog
    catalog:
      packageName: cloudnative-pg
      channels: [stable-v1]
      # renovate: datasource=github-releases depName=cloudnative-pg/cloudnative-pg extractVersion=^v(?<version>\\d+\\.\\d+\\.\\d+)$
      version: '1.27.0'
