---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudnative-pg-installer
  namespace: operators
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudnative-pg-installer-crd-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudnative-pg-installer-crds
subjects:
  - kind: ServiceAccount
    name: cloudnative-pg-installer
    namespace: operators
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudnative-pg-installer-crds
rules:
  # Manage cnpg CRDs
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [create, list, watch]
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [get, update, patch, delete]
    resourceNames:
      - backups.postgresql.cnpg.io
      - clusterimagecatalogs.postgresql.cnpg.io
      - clusters.postgresql.cnpg.io
      - databases.postgresql.cnpg.io
      - failoverquorums.postgresql.cnpg.io
      - imagecatalogs.postgresql.cnpg.io
      - poolers.postgresql.cnpg.io
      - publications.postgresql.cnpg.io
      - scheduledbackups.postgresql.cnpg.io
      - subscriptions.postgresql.cnpg.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudnative-pg-installer-other-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudnative-pg-installer-other
subjects:
  - kind: ServiceAccount
    name: cloudnative-pg-installer
    namespace: operators
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudnative-pg-installer-other
rules:
  - apiGroups: [rbac.authorization.k8s.io]
    resources:
      - clusterroles
    verbs:
      - create
      - get
      - list
      - watch
    resourceNames:
      - cnpg-subscription-viewer-role
  - apiGroups: [rbac.authorization.k8s.io]
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - create
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudnative-pg-installer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudnative-pg-installer-clusterrole
subjects:
  - kind: ServiceAccount
    name: cloudnative-pg-installer
    namespace: operators
---
# https://github.com/cloudnative-pg/cloudnative-pg/blob/release-1.27/config/rbac/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudnative-pg-installer-clusterrole
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
      - secrets
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ''
    resources:
      - configmaps/status
      - secrets/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ''
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - persistentvolumeclaims
      - pods
      - pods/exec
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - ''
    resources:
      - pods/status
    verbs:
      - get
  - apiGroups:
      - ''
    resources:
      - serviceaccounts
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - get
      - patch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - podmonitors
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - postgresql.cnpg.io
    resources:
      - backups
      - clusters
      - databases
      - poolers
      - publications
      - scheduledbackups
      - subscriptions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - postgresql.cnpg.io
    resources:
      - backups/status
      - databases/status
      - publications/status
      - scheduledbackups/status
      - subscriptions/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - postgresql.cnpg.io
    resources:
      - clusterimagecatalogs
      - imagecatalogs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - postgresql.cnpg.io
    resources:
      - clusters/finalizers
      - poolers/finalizers
    verbs:
      - update
  - apiGroups:
      - postgresql.cnpg.io
    resources:
      - clusters/status
      - failoverquorums/status
      - poolers/status
    verbs:
      - get
      - patch
      - update
      - watch
  - apiGroups:
      - postgresql.cnpg.io
    resources:
      - failoverquorums
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshots
    verbs:
      - create
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - cert-manager.io
    resources:
      - certificates
      - issuers
    verbs:
      - get
      - list
      - watch
---
apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: cloudnative-pg
spec:
  namespace: operators
  serviceAccount:
    name: cloudnative-pg-installer
  source:
    sourceType: Catalog
    catalog:
      packageName: cloudnative-pg
      channels: [stable-v1] # updateable version
