---
apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: cloudnative-pg
spec:
  namespace: operators
  serviceAccount:
    name: cloudnative-pg-installer
  source:
    sourceType: Catalog
    catalog:
      packageName: cloudnative-pg
      channels: [stable-v1] # updateable version
