---
apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: edp-keycloak
spec:
  namespace: operators
  source:
    sourceType: Catalog
    catalog:
      packageName: edp-keycloak-operator
      channels: [stable]
      # renovate: datasource=github-releases depName=epam/edp-keycloak-operator extractVersion=^v(?<version>.+)$
      version: '1.35.0'
