---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb-operator-migration
  namespace: mariadb-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mariadb-operator-migration
rules:
  - apiGroups:
      - helm.mariadb.mmontes.io
    resources:
      - mariadboperators
    verbs:
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mariadb-operator-migration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mariadb-operator-migration
subjects:
  - kind: ServiceAccount
    name: mariadb-operator-migration
    namespace: mariadb-operator
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mariadb-operator-migration
  namespace: mariadb-operator
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: mariadb-operator-migration
      containers:
        - name: kubectl
          image: registry.k8s.io/kubectl:v1.33.4
          args:
            - patch
            - mariadboperator
            - mariadb-operator
            - --namespace=operators
            - --type=merge
            - --patch={"metadata":{"finalizers":[]}}
