---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb-operator-migration
  namespace: mariadb-operator
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-operator-migration-token
  namespace: mariadb-operator
  annotations:
    kubernetes.io/service-account.name: mariadb-operator-migration
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mariadb-operator-migration
rules:
  - apiGroups:
      - helm.mariadb.mmontes.io
    resources:
      - mariadboperators
    verbs:
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mariadb-operator-migration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mariadb-operator-migration
subjects:
  - kind: ServiceAccount
    name: mariadb-operator-migration
    namespace: mariadb-operator
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mariadb-operator-migration-finalizer-v3
  namespace: mariadb-operator
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: mariadb-operator-migration
      containers:
        - name: kubectl
          image: registry.k8s.io/kubectl:v1.33.4
          env:
            - name: KUBERNETES_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mariadb-operator-migration-token
                  key: token
          args:
            - --server=https://kubernetes.default.svc
            - --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            - --token=$(KUBERNETES_TOKEN)
            - patch
            - mariadboperators.helm.mariadb.mmontes.io
            - mariadb-operator
            - --namespace=operators
            - --request-timeout=30s
            - --type=merge
            - --patch={"metadata":{"finalizers":[]}}
