[project]
name = "doa-cluster-flux"
version = "0.0.1"

requires-python = ">=3.8"
dependencies = [
  "httpx",
  "pyjwt"
]

[tool.poetry]
package-mode = false

[tool.yapf]
COLUMN_LIMIT=80
INDENT_WIDTH=2
DEDENT_CLOSING_BRACKETS=true
COALESCE_BRACKETS=true
