---
apiVersion: helm.mariadb.mmontes.io/v1alpha1
kind: MariadbOperator
metadata:
  name: mariadb-operator
  namespace: mariadb-operator
spec:
  image:
    repository: ghcr.io/mariadb-operator/mariadb-operator
    pullPolicy: IfNotPresent
  logLevel: INFO
  webhook:
    cert:
      certManager:
        enabled: true
