apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: sonoff-zigbee-dongle
spec:
  rules:
    - name: Sonoff Zigbee 3.0 USB Dongle Plus
      labels:
        feature.node.kubernetes.io/sonoff-zigbee-dongle-plus.present: 'true'
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            class: { op: In, value: ['ff'] }
            vendor: { op: In, value: ['10c4'] }
            device: { op: In, value: ['ea60'] }
            serial:
              op: In
              value: ['9ef13de3ab45ed119701c58f0a86e0b4']
