apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: water-meter-rtl-sdr
spec:
  rules:
    - name: Home water meter NESDR SMArt v5
      labels:
        feature.node.kubernetes.io/water-meter-rtl-sdr.present: 'true'
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            class: { op: In, value: ['ff'] }
            vendor: { op: In, value: ['0bda'] }
            device: { op: In, value: ['2838'] }
            serial:
              op: In
              value: ['03938241']
