---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-cluster-service
  namespace: kube-system
spec:
  secretName: internal-cluster-service-cert
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true'
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: 'kube-system'
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: 'kube-system'
  issuerRef:
    name: private-ca
    kind: ClusterIssuer
  dnsNames:
    - 'svc.cluster.local'
    - '*.svc.cluster.local'
    - '*.keycloak.svc.cluster.local'
    - '*.atuin.svc.cluster.local'
    - '*.home-assistant.svc.cluster.local'
    - '*.zigbee2mqtt.svc.cluster.local'
    - '*.mosquitto.svc.cluster.local'
    - '*.scrutiny.svc.cluster.local'
  privateKey:
    rotationPolicy: Always
