---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: louis@orleans.io
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: self-signed-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: private-ca-cert
  namespace: cert-manager
spec:
  commonName: private-ca-cert
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: self-signed-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: private-ca-cert
  secretTemplate:
    annotations:
      cert-manager.io/allow-direct-injection: 'true'
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: private-ca
spec:
  ca:
    secretName: private-ca-cert
