---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: 'dudeofawesome-owner'
subjects:
  - kind: User
    name: 'dudeofawesome'
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: 'owner'
  apiGroup: rbac.authorization.k8s.io
