---
apiVersion: v1.edp.epam.com/v1alpha1
kind: ClusterKeycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  secret: keycloak-service-account
  adminType: user
  # url: https://auth.orleans.io
  url: https://keycloak.keycloak.svc.cluster.local:8443
  insecureSkipVerify: true
