---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: kubernetes
  namespace: keycloak
spec:
  clientId: kubernetes
  name: Kubernetes
  description: Human authentication to the doa-cluster Kubernetes API
  protocol: openid-connect
  enabled: true
  public: true
  standardFlowEnabled: true
  implicitFlowEnabled: false
  directAccess: false
  consentRequired: false
  frontChannelLogout: false
  fullScopeAllowed: false
  bearerOnly: false
  surrogateAuthRequired: false
  authorizationServicesEnabled: false
  realmRef:
    kind: ClusterKeycloakRealm
    name: sequoia
  optionalClientScopes:
    - offline_access
  redirectUris:
    - http://localhost:8000
    - http://localhost:18000
  clientRolesV2:
    - name: kubernetes_admin
      description: Full administrative access to the Kubernetes cluster
  protocolMappers:
    - name: kubernetes roles
      protocol: openid-connect
      protocolMapper: oidc-usermodel-client-role-mapper
      config:
        access.token.claim: 'true'
        claim.name: kubernetes_roles
        id.token.claim: 'true'
        introspection.token.claim: 'true'
        jsonType.label: String
        multivalued: 'true'
        userinfo.token.claim: 'true'
        usermodel.clientRoleMapping.clientId: kubernetes
  attributes:
    display.on.consent.screen: 'false'
    oauth2.device.authorization.grant.enabled: 'false'
    oidc.ciba.grant.enabled: 'false'
    pkce.code.challenge.method: S256
