apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    providers:
      kubernetesCRD:
        allowCrossNamespace: true # Use Middlewares across namespaces

    entryPoints:
      web:
        address: ":8000"
      websecure:
        address: ":8443"
      tailsecure:
        address: "100.64.0.100:8443"

      traefik:
        address: ":9000"
      metrics:
        address: ":9100"

    ports:
      web:
        redirectTo:
          port: websecure
      websecure:
        tls:
          # options: default

    ingressRoute:
      healthcheck:
        enabled: true

    logs:
      # general:
      #   level: DEBUG
      access:
        enabled: true
        fields:
          headers:
            defaultmode: keep

    globalArguments:
      # allow self-signed certs for intra-cluster networking
      - "--serversTransport.insecureSkipVerify=true"
