apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    providers:
      kubernetesCRD:
        allowCrossNamespace: true # Use Middlewares across namespaces

    ports:
      web:
        redirectTo:
          port: websecure
      websecure:
        tls:
          # options: default

    ingressRoute:
      healthcheck:
        enabled: true

    logs:
      # general:
      #   level: DEBUG
      access:
        enabled: true
        fields:
          headers:
            defaultmode: keep

    additionalArguments:
      # allow self-signed certs for intra-cluster networking
      - "--serversTransport.insecureSkipVerify=true"
