apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 30m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: traefik
      version: '39.0.8'
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 12h

  values:
    providers:
      kubernetesCRD:
        allowCrossNamespace: true # Use Middlewares across namespaces

    ports:
      web:
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
      websecure:
        http:
          tls:
            enabled: true

    ingressRoute:
      healthcheck:
        enabled: true

    logs:
      access:
        enabled: true
        fields:
          headers:
            defaultmode: keep

    additionalArguments:
      # allow self-signed certs for intra-cluster networking
      - --serversTransport.insecureSkipVerify=true

    global:
      sendAnonymousUsage: false
