apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - dashboard.yaml
  - config.yaml
  - secrets.yaml
  - oidc-client.yaml
  - ../../../services/forward-auth
