apiVersion: v1
kind: Secret
metadata:
  name: forgejo
  namespace: forgejo
type: Opaque
stringData:
  admin_password: ENC[AES256_GCM,data:6d2Q2wyFg+2K4A3ruOVbXbz+Bym7TfvCROT05lFWVQ0Qy/5GqnxXviAn4wjC91Mo9ftcpxX37MK9FgN9LzkevQ==,iv:rFs3f5z/jgSGwUMyS5f6gxowrJ6eRPjHBs7G+i7gzCU=,tag:xYIFYws3nejo8Q0o2vf5TQ==,type:str]
  internal_token: ENC[AES256_GCM,data:D0YoXK4eJ1+rtvQ+qizyft6GMqOTdE+gs0j+s8KVgNUjazx7/tmWLuFljyIPDwr/zPCCl5LfqXdoYI/FmIxBBA==,iv:8GW+wpLySDYWPjMHEk/PbuxfAGbbzuRCmYDYK4dwmZU=,tag:iFgEROI3WVOO9gN4WKvFew==,type:str]
  lfs_jwt_secret: ENC[AES256_GCM,data:SulCRH39ieR/MY8pQl5rNvht9yozuOr8nP2SvCOhvYYqpycsgpD073Q4fg+ZoeukSlWtjFoV4pkHcXYAm0R3Lg==,iv:i+8T8BZu9pc01x1yVgRcRei3JeHWYnvgI4I0EOvPDoY=,tag:Csl1PnZAyMUNAKAIVjI1wg==,type:str]
  secret_key: ENC[AES256_GCM,data:Sbcbwpo8WApg78WuSMowW9/MDZCzuuaXOAOLryvk0P2XigpgY+hwZA2USDbAv+LQk4Ml9jcGEexIjnfsjkby5A==,iv:uBcNLsaaHHBgGmtElakyyy4y31NpSf7PyXsnWDk0m+Q=,tag:4GNrfd9jydILFS900VlxhA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Q3RGRDVlTHkxQ2Q1RFJj
        THN4VEEzTEZ2YXl6WEhPcnRGWlN4Rm8zZkZvCi9hQy9GK0xBRVZYRS9XYUttRU52
        ZHF0R054M1VxWStwaDlkSy9VTGhYWDQKLS0tIGpOTjdVN3NlNXdHT3A1YWljZVk2
        bXhkM21zMHlTNjVQUlFNZTl4UG9RU00KwwoFExB7zFzm+251ZTrCESSLRRMKJz2v
        bYiBnuFwu/ASrDDi/dL0e979VeFb01JGq62ujRvxCyQjY4N1AQjMcA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17dnfg660q6f6xv634dlsqzt9arungk5k3xytd68m2c94tqa3wqtqv7ew0d
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWWdxNzN1M3A4N2twbzY2
        YmRUVGw4ZTlzNCtQZGQzNVBoTmkzcHZ0bldjCkxmaW9DRDVaeFdBcU5KckNqaDJy
        ZWhoTUZjWlN2MTJIcGtBOGkvQmcwNlEKLS0tIGFPZkxhNVQ2MVVSSFRVUndQK1d6
        MkIrd3JQL0dOYmhCQjN2cy9ZU1FicGsKzxqBhU3yQHiEGIGnzkLfrVLwcDoSofAT
        SWhWOYTEa/N/Uw+5qmv2fN0LWfNVWwdDUsN6jrEA7K4DPozKAYyI3g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nu45m5ht7x7h59t4x8kalx9j084tqty27rw97xl63fp85l8w45qspgdqt0
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VXRKNkVNQmdUV2l0eHNs
        Sngvanc1MTdocmlSMWpDNDBSY1cxR29UY21JCkZTRC9aWGxSalFqVDNEdGdwNGJQ
        Y0pKQk9KdVFLNDA2TGxhY3ZWcW9MODAKLS0tIGZzellMY1N4SkFncVBsSVJKNHBk
        OGJLWVdYdGYxQTJlQUM1Z0U1MS93b3cKVxEHRiIN9/0dD8zB0GLgWh+Ur0JCd62A
        f5SDTxXK6NU23s8CScs5eOf2gqbyukLBICT+OcGxTXP2O+0srDrQcw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1y4eukgf87ug6ztmljzprzvy9q3w7e45qapkeve9jcr2sycqkl3csk2sjet
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTmxzamxDYXRoVjRRdFJH
        MmRQV3MrZ2lHSGdKazJ0T2hWU2l0dldPRWl3CjRoSTY2Y2t3dTYxQXk2T1lkZEFK
        MUJwb2xkSlk0UWYrd3JLWjFLbGhlY2cKLS0tIGJjTytXdVBSakpSZ1R3ZUlINWhy
        NkxSblArTXZQUXpmVkNFZXYwRnpZY00KZdWclvwsknCSJY2SowjDLkyoS8xJCG2Y
        p+2be3DsSxVPGXqW2n/iDy7/xIF4809lJKap9PABPM6IUFFMfx80Hg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1meara2mcpfxz9xzj0q0tur82a09paacevld6vnpfgkht2w8yayyq8y35pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-01T11:10:22Z"
  mac: ENC[AES256_GCM,data:qv7ljlkq1u5IQA50RgXS1dSa/rKzCyFRQ3Qq+LTavaSaczrUmvNdGhkwLgMVlIGkPB11ThTLFjGXafhvjCTcPt9GKvEdP64YEc0Oy8EB+dEAL9T9w3VeiIG/6kk3vJMQYH7w+OnJ2DuSn1xwAEdVo0bm/jEYIdA+iASHO1W6fB0=,iv:/FxNhE3Y8xwCCAzTcQFtJ1sRVluz2e1FCrmBnXTkRM0=,tag:GcVY+BQagdix+m61anb1Pg==,type:str]
  version: 3.13.3
