---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: forgejo-data
  labels:
    type: local
spec:
  capacity:
    storage: 25Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /mnt/forgejo
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - haleakala
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: forgejo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: forgejo-data
