---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atuin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atuin
  template:
    metadata:
      labels:
        app: atuin
    spec:
      containers:
        - name: atuin
          image: ghcr.io/atuinsh/atuin:latest
          args:
            - server
            - start
          env:
            - name: ATUIN_DB_URI
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: uri
                  optional: false
            - name: ATUIN_HOST
              value: '0.0.0.0'
            - name: ATUIN_PORT
              value: '8888'
            - name: ATUIN_OPEN_REGISTRATION
              value: 'false'
          ports:
            - name: http
              containerPort: 8888
          resources:
            limits:
              cpu: 250m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 1Gi
