---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atuin
spec:
  replicas: 1
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
        - name: atuin
          image: ghcr.io/atuinsh/atuin:18.15.2@sha256:e22d6256964bfbb59c170c14c9bd09a9687d2264817452d58726a4be379cbd47
          args:
            - start
          env:
            - name: ATUIN_DB_URI
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: uri
                  optional: false
            - name: ATUIN_HOST
              value: '0.0.0.0'
            - name: ATUIN_PORT
              value: '8888'
            - name: ATUIN_OPEN_REGISTRATION
              value: 'true'
          ports:
            - name: http
              containerPort: 8888
          resources:
            limits:
              cpu: 250m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 1Gi
