---
apiVersion: v1
kind: Service
metadata:
  name: forward-auth
spec:
  selector:
    component: forward-auth
  ports:
    - name: auth-http
      port: 4181
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forward-auth
spec:
  forwardAuth:
    address: http://forward-auth:4181
    authResponseHeaders:
      - X-Forwarded-User
