---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-base
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-config
  interval: 10m0s
  wait: true
  timeout: 5m0s
  retryInterval: 2m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/base
  decryption:
    provider: sops
    secretRef:
      name: sops-age
