---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sources
  namespace: flux-system
spec:
  interval: 1h
  wait: true
  timeout: 5m0s
  retryInterval: 1m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./sources
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 1h
  wait: true
  timeout: 5m0s
  retryInterval: 1m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure
  patches:
    - patch: |
        - op: replace
          path: /spec/acme/server
          value: https://acme-v02.api.letsencrypt.org/directory
      target:
        kind: ClusterIssuer
        name: letsencrypt
