---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sources
  namespace: flux-system
spec:
  interval: 1h
  wait: true
  timeout: 5m0s
  retryInterval: 1m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./sources
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-controllers
  namespace: flux-system
spec:
  dependsOn:
    - name: sources
  interval: 1h
  wait: true
  timeout: 5m0s
  retryInterval: 1m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-config
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-controllers
  interval: 1h
  wait: true
  timeout: 5m0s
  retryInterval: 1m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/config
