apiVersion: olm.operatorframework.io/v1
kind: ClusterCatalog
metadata:
  name: operatorhubio
  namespace: olmv1-system
spec:
  source:
    type: Image
    image:
      # renovate: datasource=docker depName=quay.io/operatorhubio/catalog
      ref: quay.io/operatorhubio/catalog@sha256:53a0b0a35a2f4681af4fbf884a4fa7fd3aa02c9b1c7dda3f8f524e53af482ee5
