apiVersion: olm.operatorframework.io/v1
kind: ClusterCatalog
metadata:
  name: operatorhubio
  namespace: olmv1-system
spec:
  source:
    type: Image
    image:
      # renovate: datasource=docker depName=quay.io/operatorhubio/catalog
      ref: quay.io/operatorhubio/catalog@sha256:7372936edbf3c43b2e67715990d8f7ff513ba2f3b0c6acd7158774d6efd6ed23
