apiVersion: olm.operatorframework.io/v1
kind: ClusterCatalog
metadata:
  name: operatorhubio
  namespace: olmv1-system
spec:
  source:
    type: Image
    image:
      # renovate: datasource=docker depName=quay.io/operatorhubio/catalog
      ref: quay.io/operatorhubio/catalog@sha256:94e5c7ed9cf58c91010b055d81782abe9d2548146d58f3167760f5675930da86
