---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: olmv1-ca
spec:
  ca:
    secretName: olmv1-ca
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: self-sign-issuer
  namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: olmv1-ca
  namespace: cert-manager
spec:
  commonName: olmv1-ca
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: self-sign-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: olmv1-ca
  secretTemplate:
    annotations:
      cert-manager.io/allow-direct-injection: 'true'
