apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - certificates.yaml
  - operator-controller.yaml
  - catalogs.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=olm
    patch: |-
      - op: remove
        path: /spec/template/spec/nodeSelector/node-role.kubernetes.io~1control-plane
      - op: add
        path: /spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms/0/matchExpressions/-
        value:
          key: node-role.kubernetes.io/control-plane
          operator: Exists
