FROM docker.io/library/alpine:3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

# Release binaries are verified before becoming part of the image. Updating the
# version also requires updating the corresponding checksums below.
ARG AVAHI2DNS_VERSION=0.2.1
ARG TARGETARCH
RUN apk add --no-cache bind-tools \
  && case "${TARGETARCH}" in \
    amd64) checksum=56042b99e9f4a39f6bc36a239e69e54d66d52cf46a3f595c9a3f08bae1602a3a ;; \
    arm64) checksum=697b02d646ff4c097efd4afff0b4701c7c669aeaefa4bc34561bfe2a93d09c91 ;; \
    *) exit 1 ;; \
  esac \
  && wget -O /usr/local/bin/avahi2dns \
    "https://github.com/LouisBrunner/avahi2dns/releases/download/${AVAHI2DNS_VERSION}/avahi2dns-linux-${TARGETARCH}" \
  && echo "${checksum}  /usr/local/bin/avahi2dns" | sha256sum -c - \
  && chmod 0555 /usr/local/bin/avahi2dns

USER 65534:65534
ENTRYPOINT ["/usr/local/bin/avahi2dns"]
