---
apiVersion: v1
kind: ConfigMap
metadata:
  name: environment
data:
  TZ: 'UTC'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration
data:
  configuration.yaml: |
    # Loads default set of integrations. Do not remove.
    default_config:

    # Load frontend themes from the themes folder
    frontend:
      themes: !include_dir_merge_named themes

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml

    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 127.0.0.1
        - 10.0.0.0/8

    homeassistant:
      auth_providers:
        - type: homeassistant
        - type: command_line
          command: /usr/bin/auth-oidc.sh
          meta: true

    recorder:
      db_url: !env_var DB_URI
      purge_keep_days: 30
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentication-scripts
data:
  auth-oidc.sh: |
    #!/usr/bin/env bash
    set -e

    >&2 echo 1

    curl="curl --silent"
    jq="jq --raw-output"

    openid_config="$oidc_issuer_url/.well-known/openid-configuration"

    >&2 echo 2

    main() {
      config_data="$($curl "$openid_config")"
      token_endpoint="$(echo "$config_data" | $jq '.token_endpoint')"
      >&2 echo 3 "$token_endpoint"

      res="$(
        $curl \
          "$token_endpoint" \
          --request POST \
          --header 'content-type: application/x-www-form-urlencoded' \
          --data 'client_id='"$oidc_client_id" \
          --data 'client_secret='"$oidc_client_secret" \
          --data grant_type=password \
          --data 'username='"$username" \
          --data 'password='"$password" \
          ;
      )"

      access_token="$(echo "$res" | $jq '.access_token')"
      >&2 echo 3 "$access_token"

      jwt_payload="$(echo "$access_token" | $jq --raw-input 'split(".") | .[1] | @base64d')"
      >&2 echo 3 "$jwt_payload"
      name="$(echo $jwt_payload | $jq '.name')"
      group="$(echo $jwt_payload | $jq 'if (.realm_access.roles | index("admin")) then "admin" else "users" end')"

      echo "name = $name"
      echo "group = system-${group:-users}"
      echo "local_only = false"
    }

    main
