---
apiVersion: v1
kind: ConfigMap
metadata:
  name: environment
data:
  TZ: 'UTC'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oidc
data:
  issuer_url: https://auth.orleans.io/realms/sequoia
  client_id: home-assistant
