---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  bootstrap:
    initdb:
      database: recorder
      owner: home-assistant

  instances: 1

  storage:
    size: 5Gi
