apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      # securityContext:
      #   fsGroup: 33
      #   fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: home-assistant-app
          image: 'ghcr.io/home-assistant/home-assistant:2024.1'
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
          envFrom:
            - configMapRef:
                name: environment
          env:
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: uri

            - name: issuer_url
              valueFrom:
                secretKeyRef:
                  name: oidc
                  key: issuer_url
            - name: client_id
              valueFrom:
                secretKeyRef:
                  name: oidc
                  key: client_id
            - name: client_secret
              valueFrom:
                secretKeyRef:
                  name: oidc
                  key: client_secret
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          resources: {}
          livenessProbe:
            tcpSocket:
              port: 8123
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8123
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 8123
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
          volumeMounts:
            - name: ha-config-root
              mountPath: /config
            - name: ha-configuration-base
              mountPath: /config/configuration.yaml
              subPath: configuration.yaml
            - name: authentication-scripts
              mountPath: /usr/bin/auth-oidc.sh
              subPath: auth-oidc.sh
      restartPolicy: Always
      volumes:
        - name: ha-config-root
          persistentVolumeClaim:
            claimName: config-root
        - name: ha-configuration-base
          configMap:
            name: configuration
            items:
              - key: configuration.yaml
                path: configuration.yaml
        - name: authentication-scripts
          configMap:
            name: authentication-scripts
            items:
              - key: auth-oidc.sh
                path: auth-oidc.sh
                mode: 555
