# Loads default set of integrations. Do not remove.
default_config:
  exclude:
    - usb

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 10.0.0.0/8

homeassistant:
  auth_providers:
    - name: Sequoia
      type: command_line
      meta: true
      command: /usr/bin/auth-oidc.py
      args:
        - !env_var oidc_issuer_url
        - 'false' # oidc_issuer_validate_cert
        - !env_var oidc_client_id
        - !env_var oidc_client_secret
    - type: homeassistant

recorder:
  db_url: !env_var DB_URI
  purge_keep_days: 30
