---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "home-assistant"
spec:
  entryPoints:
    - "websecure"
  routes:
    - match: "Host(`hass.park.gibbs.tk`)"
      kind: "Rule"
      services:
        - name: "home-assistant"
          port: 8123
      # middlewares:
      #   - name: security-no-frame-deny
      #     namespace: kube-system
  tls:
    secretName: wildcard-gibbs-tk
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  labels:
    monitor: home-assistant
spec:
  selector:
    component: app
  ports:
    - name: http
      port: 8123
