---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: 'home-assistant'
spec:
  entryPoints:
    - 'websecure'
  routes:
    - match: 'Host(`hass.park.orleans.io`)'
      kind: 'Rule'
      services:
        - name: 'home-assistant'
          port: 8123
      # middlewares:
      #   - name: security-no-frame-deny
      #     namespace: kube-system
  tls:
    secretName: wildcard-orleans-io
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8123
