apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
commonLabels:
  app: home-assistant

resources:
  - namespace.yaml
  - postgres.yaml
  - deployment.yaml
  - ingress.yaml
  - secrets.yaml
