apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
commonLabels:
  app: home-assistant

resources:
  - namespace.yaml
  - database.yaml
  - storage.yaml
  - config.yaml
  - deployment.yaml
  - ingress.yaml
  - secrets.yaml
  - oidc-client.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: configuration
    files:
      - configuration.yaml=hass-configuration.yaml
  - name: authentication-scripts
    files:
      - auth-oidc.sh=auth-oidc.sh
