---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: oidc-client
spec:
  clientId: home-assistant
  name: Home Assistant
  description: Home Assistant user login
  protocol: 'openid-connect'
  authorizationServicesEnabled: false
  # alwaysDisplayInConsole: true
  standardFlowEnabled: true
  implicitFlowEnabled: false
  directAccess: true
  public: false
  consentRequired: false
  frontChannelLogout: true
  fullScopeAllowed: true
  clientRoles:
    - 'home-assistant_admin'
  bearerOnly: false
  surrogateAuthRequired: false
  clientAuthenticatorType: client-secret
  realmRef:
    kind: ClusterKeycloakRealm
    name: sequoia
  secret: '$oidc:client_secret'
  webUrl: 'https://hass.park.orleans.io'
  # homeUrl: 'https://hass.park.orleans.io'
  attributes:
    display.on.consent.screen: 'false'
    backchannel.logout.revoke.offline.tokens: 'false'
    backchannel.logout.session.required: 'true'
    oauth2.device.authorization.grant.enabled: 'false'
    oidc.ciba.grant.enabled: 'false'
  # authenticationFlowBindingOverrides: # TODO: waiting for EDP operator ~v1.24
  #   directGrant: direct-grant-single-factor
