apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  bootstrap:
    initdb:
      database: mealie
      owner: mealie

  instances: 1

  storage:
    size: 5Gi
    storageClass: local-path

  monitoring:
    enablePodMonitor: true
