apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mealie
commonLabels:
  app: mealie

resources:
  - namespace.yaml
  - config.yaml
  - database.yaml
  - deployment.yaml
  - storage.yaml
  - ingress.yaml
  - oidc-client.yaml
  - secrets.yaml
