apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: mealie
spec:
  clientId: mealie
  name: Mealie
  description: Recipe manager at recipes.orleans.io
  protocol: openid-connect
  enabled: true
  standardFlowEnabled: true
  implicitFlowEnabled: false
  directAccess: false
  public: false
  consentRequired: false
  fullScopeAllowed: false
  bearerOnly: false
  clientAuthenticatorType: client-secret
  authorizationServicesEnabled: false
  realmRef:
    kind: ClusterKeycloakRealm
    name: sequoia
  secret: '$mealie:client_secret'
  webUrl: https://recipes.orleans.io
  redirectUris:
    - https://recipes.orleans.io/login
    - https://recipes.orleans.io/login?direct=1
  webOrigins:
    - https://recipes.orleans.io
  defaultClientScopes:
    - profile
    - email
  protocolMappers:
    - name: groups
      protocol: openid-connect
      protocolMapper: oidc-group-membership-mapper
      config:
        access.token.claim: 'true'
        claim.name: groups
        full.path: 'true'
        id.token.claim: 'true'
        userinfo.token.claim: 'true'
  attributes:
    pkce.code.challenge.method: S256
    post.logout.redirect.uris: https://recipes.orleans.io/login?direct=1
