---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: 'webhook-receiver'
spec:
  entryPoints:
    - 'websecure'
  routes:
    - match: 'Host(`flux-webhook.orleans.io`)'
      kind: 'Rule'
      services:
        - name: 'webhook-receiver'
          port: 80
      # middlewares:
      #   - name: security-no-frame-deny
      #     namespace: kube-system
---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: doa-cluster
  namespace: flux-system
spec:
  type: github
  events:
    - 'ping'
    - 'push'
  secretRef:
    name: webhook-token
  resources:
    - kind: GitRepository
      name: flux-system
