apiVersion: apps/v1
kind: Deployment
metadata:
  name: esphome
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
        - name: esphome
          image: ghcr.io/esphome/esphome:2026.6.4@sha256:20c12b47f53d31c4d2b1eeeec03ef93e414a710f5834220d02353ec575bca1c6
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 6052
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /config
        - name: config-git-sync
          image: alpine/git:v2.54.0@sha256:697cb1c85aefc5724febaec2202a974e0d66f6abb6be91a9a86d0c8757af692a
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - /usr/local/bin/git-sync.sh
          env:
            - name: GIT_REPO_DIR
              value: /config
            - name: GIT_REMOTE
              value: ssh://git@github.com/dudeofawesome/esphome-devices
            - name: GIT_BRANCH
              value: main
            - name: GIT_SYNC_INTERVAL
              value: '300'
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: config-git-sync
              mountPath: /usr/local/bin/git-sync.sh
              subPath: git-sync.sh
              readOnly: true
            - name: config-git-ssh
              mountPath: /etc/git-secret
              readOnly: true
      restartPolicy: Always
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
        - name: config-git-sync
          configMap:
            name: config-git-sync
            defaultMode: 0555
        - name: config-git-ssh
          secret:
            secretName: esphome-config-git
            defaultMode: 0400
