apiVersion: apps/v1
kind: Deployment
metadata:
  name: esphome
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
        - name: esphome
          image: ghcr.io/esphome/esphome:2026.8.1@sha256:dda49fd0079ed818c2859b52ffeb2c07263349c2d3cc601a0539fd3a8f855d21
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 6052
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /config
        - name: config-git-sync
          image: alpine/git:v2.54.0@sha256:d301ddc314bb6531726d37fbd435b5d736296ad0f77e54246ae78ef74031729d
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - /usr/local/bin/git-sync.sh
          env:
            - name: GIT_REPO_DIR
              value: /config
            - name: GIT_REMOTE
              value: ssh://git@github.com/dudeofawesome/esphome-devices
            - name: GIT_BRANCH
              value: main
            - name: GIT_SYNC_INTERVAL
              value: '300'
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: config-git-sync
              mountPath: /usr/local/bin/git-sync.sh
              subPath: git-sync.sh
              readOnly: true
            - name: config-git-ssh
              mountPath: /etc/git-secret
              readOnly: true
      restartPolicy: Always
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
        - name: config-git-sync
          configMap:
            name: config-git-sync
            defaultMode: 0555
        - name: config-git-ssh
          secret:
            secretName: esphome-config-git
            defaultMode: 0400
