apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: music-assistant
commonLabels:
  app: music-assistant

resources:
  - namespace.yaml
  - deployment.yaml
  - ingress.yaml
  - storage.yaml

generatorOptions:
  disableNameSuffixHash: true
