apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
commonLabels:
  app: cert-manager

resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - ingress.yaml
  - issuer.yaml
  - secrets.yaml
