apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: influxdb
spec:
  interval: 30m
  chart:
    spec:
      chart: influxdb2
      version: '2.x'
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system
      interval: 12h
  values:
    ## Configure resource requests and limits
    ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
    ##
    resources:
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      # limits:
      #  cpu: 100m
      #  memory: 128Mi
      # requests:
      #  cpu: 100m
      #  memory: 128Mi

    ## Tolerations for pod assignment
    ## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
    ##
    tolerations: []

    ## Affinity for pod assignment
    ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
    ##
    affinity: {}

    ## Extra environment variables to configure influxdb
    ## e.g.
    # env:
    #   - name: FOO
    #     value: BAR
    #   - name: BAZ
    #     valueFrom:
    #       secretKeyRef:
    #         name: my-secret
    #         key: my-key
    env: {}

    ## Create default user through docker entrypoint
    ## Defaults indicated below
    ##
    adminUser:
      organization: 'orleans'
      bucket: 'scrutiny'
      user: 'scrutiny'

      ## The password and token are obtained from an existing secret. The expected
      ## keys are `admin-password` and `admin-token`.
      ## If set, the password and token values above are ignored.
      existingSecret: influxdb

    ## Persist data to a persistent volume
    ##
    persistence:
      enabled: true
      ## If true will use an existing PVC instead of creating one
      useExisting: true
      ## Name of existing PVC to be used in the influx deployment
      name: influxdb-data

    ingress:
      enabled: false
