# Reference:
# https://github.com/keycloak/keycloak/discussions/12594
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrutiny
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
        - name: scrutiny
          image: ghcr.io/analogj/scrutiny:v0.9.3-web@sha256:a8c488a625bb79701338403b84a6d025f0884a35d348e412335bbd090f06ff3f
          env:
            - name: SCRUTINY_WEB_INFLUXDB_HOST
              value: influxdb-influxdb2
            - name: SCRUTINY_WEB_INFLUXDB_PORT
              value: '80'
            - name: SCRUTINY_WEB_INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb
                  key: admin-token
            - name: SCRUTINY_WEB_INFLUXDB_ORG
              value: orleans
            - name: SCRUTINY_WEB_INFLUXDB_BUCKET
              value: scrutiny
            - name: SCRUTINY_NOTIFY_URLS
              valueFrom:
                secretKeyRef:
                  name: ntfy
                  key: url
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 10m
              memory: 400Mi
            limits:
              cpu: 300m
              memory: 500Mi
          volumeMounts:
            - name: config
              mountPath: /opt/scrutiny/config
          # readinessProbe:
          #   initialDelaySeconds: 30
          #   timeoutSeconds: 30
          #   httpGet:
          #     path: /realms/sequoia
          #     port: 8080
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: scrutiny-config
