---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: scrutiny-collector-api
spec:
  entryPoints:
    - websecure
  routes:
    - match: 'Host(`scrutiny-api.orleans.io`) && PathPrefix(`/api/`)'
      kind: Rule
      services:
        - name: scrutiny
          port: http
      middlewares:
        - name: basic-auth
          namespace: scrutiny
  tls:
    secretName: wildcard-orleans-io
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
spec:
  basicAuth:
    secret: api-basic-auth
