apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scrutiny
commonLabels:
  app: scrutiny-master

resources:
  - namespace.yaml
  - database.yaml
  - storage.yaml
  - deployment.yaml
  - ingress.yaml
  - secrets.yaml
  - ../../../../services/forward-auth

patches:
  - patch: |
      - op: replace
        path: /spec/forwardAuth/address
        value: http://forward-auth.scrutiny.svc.cluster.local:4181
    target:
      kind: Middleware
      name: forward-auth
