---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: oidc-client
spec:
  clientId: scrutiny
  name: Scrutiny
  description: Storage device monitoring
  realmRef:
    kind: ClusterKeycloakRealm
    name: sequoia

  protocol: 'openid-connect'
  # alwaysDisplayInConsole: true
  standardFlowEnabled: true
  implicitFlowEnabled: false
  directAccess: true
  public: false
  consentRequired: false
  frontChannelLogout: true
  fullScopeAllowed: true
  bearerOnly: false
  surrogateAuthRequired: false
  clientAuthenticatorType: client-secret
  authorizationServicesEnabled: false
  secret: '$oidc:client_secret'
  webUrl: 'https://scrutiny.orleans.io'
  # homeUrl: 'https://scrutiny.orleans.io'
  attributes:
    display.on.consent.screen: 'false'
    backchannel.logout.revoke.offline.tokens: 'false'
    backchannel.logout.session.required: 'true'
    oauth2.device.authorization.grant.enabled: 'false'
    oidc.ciba.grant.enabled: 'false'
