apiVersion: v1
kind: Secret
metadata:
  name: oidc
stringData:
  client_secret: ENC[AES256_GCM,data:LIREiUqZFIk1/4WR3GUDSQluCq4VlK7gAecrnLL4kGq9rGYd25Q7QT6bfnIxpyHBydnP4BjPGRFqKUpvWHo02Q==,iv:2lssFLSAmWqC4dPBh80uWfckiCiHBf++TvM3TcXB9tY=,tag:IiG+lLJStbcd7tBYOEtdxQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVkFCOGVXYWd1bjQxZWZD
        dWJJYVRMTEVXME8xcmlXR29UWEo3bWhUejFJCmd2eDU2ZnlFQzZvQzVzbXRnMWxM
        WUpnanQ5TnczY1B1T2hLYkZtZUNjR1EKLS0tIHZoeXlCcnJoYnE5Tmw1MHo0Ynda
        bGQ4dmVNODl4eHNHTWg4aVNXVEFqTk0KhFOID59jQBA6laDWWZDJSHqqDp7y7vey
        uV0GBmWIAGtSMgsfvTloQwpqKgj5h5j5L14Y/tn3gjbZQohDCbsjfQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17dnfg660q6f6xv634dlsqzt9arungk5k3xytd68m2c94tqa3wqtqv7ew0d
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYc0V6NnZzbStUQzN4M2pF
        S0Y4dG1XN1JJcHdOTm4yREtDL0VPM2dkc3pZCjljQjczVU1QcnBMYVgxeGo3aGVw
        a1dVNjN0Vk94a0ZvSENkWGN5WmwzaU0KLS0tIEYxZ0NKb1FwTnlCOXFzTGJaTXVz
        Q25KVUNaTFRGUnMrdmh4S3FRWG04ejAKSz0/SiqWzRgKRizzX8gygZb1GM7ZBVVX
        fmBrn4L8RlXUVHM6HDJ9ZKncWKHbb4CVDmXfOlMaNd+F4eOtv/0DuA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nu45m5ht7x7h59t4x8kalx9j084tqty27rw97xl63fp85l8w45qspgdqt0
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RHJaRUhXQ2NuaXA1YVIr
        cDNjSW1UVEJqRHZhQVVIemhCWCtZcmVCdEhZCnNRZGZBYWovejlVZ3J4UGdVNWZM
        WE9PcWVVRGZpOGtJa3UzRkE0NXhwdUUKLS0tIGYwOFp4NFhWUm1IYjBZNGk0TTJL
        RHJOUjM1N1lqZ21SSnFFUUJQbjM1ZDAK1R/nKIboIoPbsXvLlo9bkWCja592Ifmn
        hAT4OYuLcNcna6gqzrlhzWzuxBxlK5TPdT/EXIvD1UXmBIepGqTE2w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1y4eukgf87ug6ztmljzprzvy9q3w7e45qapkeve9jcr2sycqkl3csk2sjet
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmOXVwR3FYSnM3UlNBN3E5
        bTZpTEhiVmxzTHNwazFUdm8reVFHWExGNmlZCmVFVkpEZFd6TFlLSktEK2QwT0Ew
        QjhLNi83Z0NOaTNTTVRsZEZWK0NhZGMKLS0tIDFFR2JjMHR5RjFqamNtQlZyTlox
        RGVWQUxZZDdHd2tmMHlZZ1lUemNFUTAKDAemorQmPEvITaIBVmrBKVyrGXp3SiwJ
        mo4WzLAFVYG70GsbtZqvTOU6gxxTFRcAo3hSKoLTqxtoMAtMW2NNyA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1meara2mcpfxz9xzj0q0tur82a09paacevld6vnpfgkht2w8yayyq8y35pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-17T19:52:59Z"
  mac: ENC[AES256_GCM,data:9g53wgLYHDfbIIpMhcqZE0USXX4I6pkKlh83rZWf6ftim8ifWArRB9nb+Dt81e9byQattCIJ+MHDRNvdCBp17Y0m6BFub+J9Nub3BSDUP32WRWypBinbRFsf2Gxrn/aSHY8bgFH79l6hzUMmpg+u7HdnmtSAqJd+2HekufIIvrc=,iv:t+MQ8Mr1sNEWqZpWu4mdnz/Ux78YEJNSnLYvkxW5NVU=,tag:ZwwNXykxBybIPoUsXQ8A3A==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: forward-auth
stringData:
  secret: ENC[AES256_GCM,data:tC0Q0VhTXN+Q0zQKbPHuThJTdVUltJMbVeQdBeEA/Y+tKaXJMQ0NhG2PlufRTz2H9SmCOr7eAQWcDbX2JG5xBQ==,iv:vxI7caFW1Gqm6tVWIJqO+yJJsHHx6uGYGaq7274N7VY=,tag:BG9Y8S+Imj8Y8L7EjACV9Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVkFCOGVXYWd1bjQxZWZD
        dWJJYVRMTEVXME8xcmlXR29UWEo3bWhUejFJCmd2eDU2ZnlFQzZvQzVzbXRnMWxM
        WUpnanQ5TnczY1B1T2hLYkZtZUNjR1EKLS0tIHZoeXlCcnJoYnE5Tmw1MHo0Ynda
        bGQ4dmVNODl4eHNHTWg4aVNXVEFqTk0KhFOID59jQBA6laDWWZDJSHqqDp7y7vey
        uV0GBmWIAGtSMgsfvTloQwpqKgj5h5j5L14Y/tn3gjbZQohDCbsjfQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17dnfg660q6f6xv634dlsqzt9arungk5k3xytd68m2c94tqa3wqtqv7ew0d
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYc0V6NnZzbStUQzN4M2pF
        S0Y4dG1XN1JJcHdOTm4yREtDL0VPM2dkc3pZCjljQjczVU1QcnBMYVgxeGo3aGVw
        a1dVNjN0Vk94a0ZvSENkWGN5WmwzaU0KLS0tIEYxZ0NKb1FwTnlCOXFzTGJaTXVz
        Q25KVUNaTFRGUnMrdmh4S3FRWG04ejAKSz0/SiqWzRgKRizzX8gygZb1GM7ZBVVX
        fmBrn4L8RlXUVHM6HDJ9ZKncWKHbb4CVDmXfOlMaNd+F4eOtv/0DuA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nu45m5ht7x7h59t4x8kalx9j084tqty27rw97xl63fp85l8w45qspgdqt0
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RHJaRUhXQ2NuaXA1YVIr
        cDNjSW1UVEJqRHZhQVVIemhCWCtZcmVCdEhZCnNRZGZBYWovejlVZ3J4UGdVNWZM
        WE9PcWVVRGZpOGtJa3UzRkE0NXhwdUUKLS0tIGYwOFp4NFhWUm1IYjBZNGk0TTJL
        RHJOUjM1N1lqZ21SSnFFUUJQbjM1ZDAK1R/nKIboIoPbsXvLlo9bkWCja592Ifmn
        hAT4OYuLcNcna6gqzrlhzWzuxBxlK5TPdT/EXIvD1UXmBIepGqTE2w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1y4eukgf87ug6ztmljzprzvy9q3w7e45qapkeve9jcr2sycqkl3csk2sjet
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmOXVwR3FYSnM3UlNBN3E5
        bTZpTEhiVmxzTHNwazFUdm8reVFHWExGNmlZCmVFVkpEZFd6TFlLSktEK2QwT0Ew
        QjhLNi83Z0NOaTNTTVRsZEZWK0NhZGMKLS0tIDFFR2JjMHR5RjFqamNtQlZyTlox
        RGVWQUxZZDdHd2tmMHlZZ1lUemNFUTAKDAemorQmPEvITaIBVmrBKVyrGXp3SiwJ
        mo4WzLAFVYG70GsbtZqvTOU6gxxTFRcAo3hSKoLTqxtoMAtMW2NNyA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1meara2mcpfxz9xzj0q0tur82a09paacevld6vnpfgkht2w8yayyq8y35pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-17T19:52:59Z"
  mac: ENC[AES256_GCM,data:9g53wgLYHDfbIIpMhcqZE0USXX4I6pkKlh83rZWf6ftim8ifWArRB9nb+Dt81e9byQattCIJ+MHDRNvdCBp17Y0m6BFub+J9Nub3BSDUP32WRWypBinbRFsf2Gxrn/aSHY8bgFH79l6hzUMmpg+u7HdnmtSAqJd+2HekufIIvrc=,iv:t+MQ8Mr1sNEWqZpWu4mdnz/Ux78YEJNSnLYvkxW5NVU=,tag:ZwwNXykxBybIPoUsXQ8A3A==,type:str]
  version: 3.13.3
