apiVersion: v1
kind: Secret
metadata:
  name: oidc
  namespace: grafana
type: Opaque
stringData:
  client_secret: ENC[AES256_GCM,data:nRuFufPiKcylZRI0x5sRZUDR99z/MiDyZ+5x0LCK4oDmpl8yXzlM2BneLsZFhYH4dX2SnKz/meUxxVU8mr3g8Q==,iv:7oRTiCLhMxcOhX+TE6MyXyYu64r3vYuLYPdvENv4ttM=,tag:KkaTE/237Cyup3z5WYHAZg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTFhZdlQ3YUV3Tk5DSHBX
        WFZ6alhNZTBBNW11ekRSbFgxZlpFRS9DTFRnCjJMMjEybWV4WU91dEExTFRuTHJL
        SXJKS3k2Wk1yVE01S3cxa2xvQjl0SU0KLS0tIHovZUliVldFV0hvUy9HY1dqR3Nq
        TVlaWWZwckVPU3lhdEZiU1IyQTBGUE0KhbHkA8fbsuKqtzXs/EvaoS5gjDAcVlmv
        6GNKI+7WTVSLC/q1lUDCHK24GbnwOPcg49fzPDbczWH4qTD2o9YU4Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17dnfg660q6f6xv634dlsqzt9arungk5k3xytd68m2c94tqa3wqtqv7ew0d
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpa1hENHhTRnROZjI3WGxu
        VG8veGY0bEtrOEVqQTR3bU90bW5KajRscENrCjNqOEdkSjZGandXR0JtT1FVOFE0
        a0l1bWFoZWtJQk5nQysyNll4SnZXSGcKLS0tIFZhcFduSVhPL0oyUDJ1TVFmSG9a
        YStnY0Q1b2FFM1RZRmh5ZUtHa2RPNkUKOW3MmgqCBOqRMCJ9cX/o54zYuvObYq56
        clkVfh6PJFbOtSIGhzQH5/ABvVwJ57hob3tShVntaTtlvaGLVj+nUw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nu45m5ht7x7h59t4x8kalx9j084tqty27rw97xl63fp85l8w45qspgdqt0
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwR3EvL1hQQkVuMGZVSFI1
        TjhmQW90NDd5U3Jma2tOWmZKNGY5d2VHSUZVCmRXNjNVQk1SQXZGN1ZrK0JTUmR3
        RUdZbGJweVJvbU1RR21uemZSN2tRdHMKLS0tICtqck9NQ3Vsb0lMdE1DajlrbE8y
        a0F2VWRka1hEZzlJcFlVMTd6a3FUcGsKTUhsoRy07Lv8nGebjxxytOKx8Ow5Hq7N
        TQwkM+nk7vNJecLMGgWZ7KP0MAbiTeCkEW0d/4vZlZZz2pNSZvPrRw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1y4eukgf87ug6ztmljzprzvy9q3w7e45qapkeve9jcr2sycqkl3csk2sjet
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZzNYQWJHclZUZ0ttSnla
        RGNHZkhDZnAxK1lVVUxwR3Y3K1ZqcXBLYVhFCml2QzdaZXBnQmZNQmNwdndRKy9O
        cFBFbklwWlFiOHRIQ2E3U2xuSTZVYzAKLS0tIHc4bjlEL1BqZi8zajByYmlOT3NY
        RE5MUzdkNnMwbW85eTY2ZjBRWFFDZm8KvKOzqcVAefBmOWLGReYsT9IaR7NPwa26
        3sJ/MlXrTzrP53Y/zUXfbs38zIF+oZhhrKi6wNwEYvLBvJtQPrvyvw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1meara2mcpfxz9xzj0q0tur82a09paacevld6vnpfgkht2w8yayyq8y35pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-09-15T21:39:47Z'
  mac: ENC[AES256_GCM,data:mLCSziobW6Dt/AHaxSp9di8c70CwhTCQcZ5MEuwUytUfA6lAjkFcfPgbR5ldYk8ypnkYUpMPEoNcVrecIy1MI0+yM302Ww2qQNJylEa0VH8v5yr0dyANyYGuDkZeCcVaWiRyeg4U6f4USnEN6ghvrRoXs4CM2ip0/fRFp5inBi0=,iv:d/GGahZ04SVxzCc9Oo0mWCdVPyWzlFQBDk2wkU6+PsQ=,tag:Eute/zpEES5Z80/y0CvK0A==,type:str]
  version: 3.13.3
