apiVersion: v1
kind: Secret
metadata:
  name: oidc
  namespace: forgejo
type: Opaque
stringData:
  client_secret: ENC[AES256_GCM,data:bhnBPBKCTzKfS+VgvXPY3f6rpb7ob+r3IRWvoABZbaLndB2mMDjEWrnWOVFMsnD63D4cZdjTAdaCfRkdIH7RDg==,iv:KCwE/DgEIOMYYRW+XkeWwRufJk5wCXpIFfa+Ntw7Mm8=,tag:h3LhdaWad08Wum6K0AwBlQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUmFNSGFIS1U4ZTNyaVVq
        aWlUZHFvSldBRmxOaTd0ZjdyVHdsNnBOb2hZCmFXYzVzZE5jeVBOajJPS2dXTnFj
        b2lhQjJIVC9ZVGZEYUdveUJjLzdvQlkKLS0tIG5QQzRVRXN0RXN6Zkh5akM2VkZE
        TmF2WndNbXhmRW5HQlVtN05yTVJHcHcKqi/stsoBsAUXVhEzDJybjkvspayOTdH0
        5FEm5VxaKCumQrBT+Vj7znzzuvpp5ZXrk+VF4OK5QEW76lDl232zew==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17dnfg660q6f6xv634dlsqzt9arungk5k3xytd68m2c94tqa3wqtqv7ew0d
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwamRaOHZSTG42K0VTYzYv
        RllEaEhyQ1pGTFZMQ2RoS3dxUEhyamlMTjFJCnhKUWZoV0svWE40Rlo2a21nQlg0
        U1hBT0NNbFdrK0dwRGVjV2FUVU1sVkkKLS0tIFRwUFBnRFQ3VGNMeEJkN1h2ZE5G
        Y3pDYittbnE5aURDUE1UKzFBOGpyOXMKcdMFZFOUtB6wxd+1iPdf80UpLBhpns4B
        qmG32xLrcnV5PlEcOWyBbUztjj+kH+bWy6uFDCljdP/jcNQ2Qh5tvg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nu45m5ht7x7h59t4x8kalx9j084tqty27rw97xl63fp85l8w45qspgdqt0
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdkxaU3ZxNFlUUmw3aXlP
        VEhoQVZjK0MrRGJXQ09WRjlRQkVDUHA4SzJNCnRneExHd1RINnVHazlGeUlmZGsw
        NkcvWko2SitBZEpQeTlndy9kK1FWQkEKLS0tIFUvRzZrUE9aeW52OFpPTG1kOS90
        SW0wRUM4YXVwMkdqR0RjemlSclZPY0UKFC5Odzj9ExCzIURxPYINLPy92YAKRvM8
        JDr7lhyy7TitzsTYlBiz9wFmofLKiguKxmn2fyrRBEr/nQ25kdm2Jw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1y4eukgf87ug6ztmljzprzvy9q3w7e45qapkeve9jcr2sycqkl3csk2sjet
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdnBmOWMvWHkrL01MamQ1
        akRsd3dYMXRoWFFFU0RaYlRoeVFxZ05GTFFVCkV4N2hrMXFqU1FaV3VKV291WXRN
        dDBkQzlyUWRER2ZVQzZkQVFGa3hVRHcKLS0tIDRHcko2V1ZjanVhZ080UkgyUHBU
        c2FoZWRMeHpULzQ2Q2Q5clFPWW53aW8K8b+a9GTema44AVtt68OYz5CiVr5a8SsV
        s+wGS8MoG00yNO+wBOCLvahvL590Kby3zjOf7JNbE1sIEDCFuTpt3g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1meara2mcpfxz9xzj0q0tur82a09paacevld6vnpfgkht2w8yayyq8y35pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-01T11:10:22Z"
  mac: ENC[AES256_GCM,data:Xk9/wvVnU3cLH0lh60wQbZRI5/Cudi8wAlrRudCmujuV6jTgr/mqpnehyAqUxrke3Pj9McFthLrjwzA5jWxbgeTtxm9ATAdc141h3ab5j7Nkci5qFQGJP8URUfqkDVqm+fXb6WE21VhOFtqKNYrv5u1cWlFOw2hHxSQb6oOQ9xI=,iv:7fUeLQE5ec3yhX1/lJ+q+e3Ivz/ATZCj9IjQrzvMx+g=,tag:OrEKbvqKg4wLW+wk6dM62Q==,type:str]
  version: 3.13.3
