---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: flux-system
spec:
  chart:
    spec:
      chart: rook-ceph
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rook-release
      version: '>=0.0.1'
  install:
    crds: Create
    createNamespace: true
  interval: 1h0m0s
  releaseName: rook-ceph
  targetNamespace: rook
  upgrade:
    crds: CreateReplace

