LogLevel warn
Listen 0.0.0.0:631
Browsing Yes
DefaultShared Yes
WebInterface Yes
DefaultEncryption Never
PreserveJobFiles No
PreserveJobHistory No

<Location />
  Order allow,deny
  Allow @LOCAL
</Location>

<Location /admin>
  Order deny,allow
  Deny from all
</Location>

<Location /admin/conf>
  Order deny,allow
  Deny from all
</Location>
