apiVersion: v1
kind: Secret
metadata:
  name: ntfy-alertmanager
  namespace: monitoring
stringData:
  token: ENC[AES256_GCM,data:os+7IPX5xZXvtCtl2MPITq8RNMnCYkZgRtpL9ArsDpw=,iv:7Rgy03kzNXkF4nISIDtWU9FRbIAhrmcbcAm+hkox1os=,tag:/rtU7ctGU/keVvgHhLEJXQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0eVBXTmEzV3JhOWZwNS85
        SUpSZUVOV1ZnSGpOTFVXMDdkY011Q3hiVkRZCktDa05nSGhZL2podkxJWm1nMmdO
        Q2RCK2hTamFPWUt0YmhsaVVjYUlsbjQKLS0tIFg1WURvN3JOOWRyR3NDNk9zeStK
        STJZbnNwMzRzT3NQeEpLM2EwYUpoK2MKExEqcBLzFFSzurHYjMZ7naPh2bPCgtTV
        pFo2HJSI6qxM1qHPrfUCD5qTYQoH5Rz1O3vm5SNG/IEKojOY5SAAiw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17dnfg660q6f6xv634dlsqzt9arungk5k3xytd68m2c94tqa3wqtqv7ew0d
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZjJ6ek5uWkR2ei9xV2hY
        UmpJVzRaSzR4cTBlcVpiZkZoblZKQm5jcVRnClVsMWx0KzVDcnVobC9jU3JoM1JG
        NjhBaHZsL1lsaVBzNGZZRncwQ0toWlEKLS0tIDliT0ZzSElJT2xIY2xsUjFqbmY5
        N2N0WW5NbENWeHd2TzZPSklzUHordjAKYxNITO8jPAcDpLnh4tinFKqqNLkQEgWj
        /XbNk4qQDn5GcJuTlNfaabljFea+8Sp7qbPhYd93IuvMbKLOJ0MOgQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nu45m5ht7x7h59t4x8kalx9j084tqty27rw97xl63fp85l8w45qspgdqt0
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUjhXT0pnZUpnYTNROGMw
        cHNRVkZoUXFTU0I3Ymk4S3h2RXRTcHlsbldjCjdsU29JMWRVc2Vablh0Z1BXUG9J
        SU5iajA0MnlUWHF1Vml4KzFoZUQvam8KLS0tIEk4UVUyWCs4T2NIbHVjYit6eFJu
        MlpZc1o5c3k5QSt0a0FTemtma3pZNVUKkstFpH5Y+w33EtMPwU7Ju01qItIei4jk
        v74BwZIh7JYEfdA4TLSDXwEUdSg6WeppgYFFIU088eZovOnTmrx+JA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1y4eukgf87ug6ztmljzprzvy9q3w7e45qapkeve9jcr2sycqkl3csk2sjet
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUblMvYW1la0paRGVCTU1S
        NlpBbWI2dTNxRkJkS3FZbzNRdElCeENKNzJnCjhVTlovb3BTeFg4ZVVqN0ViblR1
        ZDRWUTgwdEZxcmlLOWMxS3NuTllySGcKLS0tIE13cnl1bjVSRUtOcWViNEtrRmpH
        QUdBNCtkc1RxdU5FakI5NDlrY2NhM00Kmt9oJwSiXYcRaOPmXpvbysAKcCObU3Gv
        9hARCsyQbRjyO5DNU6tGwurkz0F6wn13GoPfHWOdzh4Qpi9fBdxVuA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1meara2mcpfxz9xzj0q0tur82a09paacevld6vnpfgkht2w8yayyq8y35pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-09-12T06:18:54Z'
  mac: ENC[AES256_GCM,data:ImhLl/HJLJOeF1zYDzAlDTDdZGcCv11IuoQWs9rbN7MaJsHyFbn4JvnsXRNR6n3o9xOVkdgV+QyWdn2H3hpyAiEKjzV0XlQ0fXk+rHMZncYSxC+gEA1qH4pYKNQE6QhRs/z15ycLzhpBTCn9a4DR84DS9oJPP/mzWxOnWuT1cbM=,iv:r54jxVFnS+zWAZDXhKEDkVtugrLBWmomJWHoeoSf3mg=,tag:fYdORNTySVyGjdDMXBui2Q==,type:str]
  version: 3.13.3
