---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  labels:
    app: ldap
    environment: production
    tier: backend
  name: ldap
  namespace: flux-system
spec:
  chart:
    spec:
      chart: openldap
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: geek-cookbook
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: production-base

