apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: filaman
commonLabels:
  app: filaman
resources:
  - namespace.yaml
  - database.yaml
  - storage.yaml
  - deployment.yaml
  - ingress.yaml
  - oidc-client.yaml
  - secrets.yaml

configMapGenerator:
  - name: config
    envs:
      - config.env
  - name: startup
    files:
      - startup.py
