---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flux-kustomization-status-reader
rules:
  - apiGroups: ['kustomize.toolkit.fluxcd.io']
    resources: ['kustomizations']
    verbs: ['get', 'list', 'watch']
