apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration
data:
  mosquitto.conf: |

    # enable listener
    listener 1883

    # TODO: require auth
    # Disable authentication
    allow_anonymous true
