apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 30s
  resyncPeriod: 10m
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: alertmanager
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: Alertmanager
    uid: alertmanager
    type: alertmanager
    access: proxy
    url: http://monitoring-kube-prometheus-alertmanager.monitoring.svc.cluster.local:9093
    editable: false
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: false
  resyncPeriod: 10m
