apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: grafana
stringData:
  admin-user: ENC[AES256_GCM,data:9am/O4Q=,iv:jAZvr7FpQSsx5ogfDSgb/OMJcYNJa+VaS0I7eScbHkI=,tag:wD85P30IflEdkJhEX5+WJQ==,type:str]
  admin-password: ENC[AES256_GCM,data:zaR147Jb3fIrZjDdVswhGk27Uq462HUDabAkzp43z//tCs7AbCs4NVLTkA==,iv:eOcXUreASQ8nclFfqnLHC5+VwzmQ1NCV25FhxABvsUE=,tag:toh1aycs8SdEgYK1waxWaA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWnptb3JQSnZUSFU2RzVS
        QTZVejlYN1cxK3NBdkpBM2ZtK1NpamptV0dZCjBBY25iaGcwRFk3elZockQ2RGh6
        TXhINkJiOGFwaFpyVHBja016UEZFZW8KLS0tIFNyd1R2KyswTjRLQ1E3WWU4RGt4
        SU9MUGdybWUrTzJwamtyb2N4VTRZZ2MK5LgEyo85FH4kmsIKCHMtCt8zsf4EG4tT
        WHXHw+4Pt2+6X6bQsFqVpp+nZ+e7T1vMKA5sJ899jrRYKfWNH90IIA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17dnfg660q6f6xv634dlsqzt9arungk5k3xytd68m2c94tqa3wqtqv7ew0d
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydFo0LzBCR29HWWlFRUFD
        QktDbmxqMkJqTHNSbUJQOVZOL1M5c3ZjV0FjCkhHUWJFa2NUbEdJTWNRU2dBMU1h
        VERpbUFzRGl5ZHVKSG9KK2RkVlBFc1UKLS0tIE5aU1haN0o1WUlWNzRweS80Tjhv
        S2hQRkZFVkNJcXBjRXR6YVFCR2xMTmMKPKTjyWwFKuhCQ4p/nqaAceBK0zvDWJDv
        1U2asEtA8PrhBGu2JLPabjO0X9E+IyXCIuwWBGslVKXlptfJ+BbSMA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nu45m5ht7x7h59t4x8kalx9j084tqty27rw97xl63fp85l8w45qspgdqt0
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYVZNRWRYVTRZT3dCc1Mx
        U3ZjMnExdFo5OGFJeHltM1EzRGlNemExSndRCldzT0I0QkZxeElDY3ZOMHF3aXFC
        eUxDRzdNUVBZZXdCaW1mRWhqK0EweTAKLS0tIHdyWUxhbEIyL05BUVZRVkpBTjFl
        cVNnSyszVHBsSm0yK3VvRjJNanFja2cKpCalZSLTxcKmh4uSi2MBdT4Sh7Yb2xVT
        zRRIqrfQ+Dv/xzI+Ip7pAO2yMrfMNZJ10C3tHQNL+5Kc2E55uPRQGA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1y4eukgf87ug6ztmljzprzvy9q3w7e45qapkeve9jcr2sycqkl3csk2sjet
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOHhLQlJ2djJQN1ZXZ3RZ
        cnpvZDE2dkVyeVRVeTRuYms4bnV0VDZKV2lFCnRwRU1KdjNxbFg0SE5qUlJkSUlV
        cE5neWVIUUZyOFU3RzRhYzJMOXNzYnMKLS0tICsyVWVYNHpDTmtkNzhwaG82VDcx
        K1FFTEtORmt1Nmk4WFRPYmxieVpUWEUKfEjsWVT7wH9CaV8fJNGkFsNlWnatmzPS
        cnKyAoJtKbMyLewnUEvhw/24I2cDY++ajk6MDxpulltOGgUHN3K6BA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1meara2mcpfxz9xzj0q0tur82a09paacevld6vnpfgkht2w8yayyq8y35pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-09-12T06:18:54Z'
  mac: ENC[AES256_GCM,data:nHvgCJ7BGY4IIMEIslaSH3R2I9gAnsnMUVaPgkZqDS6itNkD54R3zNswW4mQj3dKKDklRye6oa1cRNr1oFcuxdrGEP9M+rhFaM7WNMw/tfzJcvw3JKi+ellvMUPAYT+HDjXwh74ia2SNEf0RvEiSWGGSYDb36eciweGkuEocNkA=,iv:Bnlkq/S4oBtc4AWQfHWEjnubxhxFMzinOu29utiugeA=,tag:Vhvoz+EN5NTYJdgBh+GkhQ==,type:str]
  version: 3.13.3
