---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hermes
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`hermes.orleans.io`)
      kind: Rule
      services:
        - name: hermes
          port: 9119
  tls:
    secretName: wildcard-orleans-io
