apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uptime-kuma
labels:
  - pairs:
      app: uptime-kuma
    includeSelectors: false
    includeTemplates: true

resources:
  - namespace.yaml
  - storage.yaml
  - database.yaml
  - deployment.yaml
  - ingress.yaml
  - network-policy.yaml
